const ROLES = {
  OWNER: 'owner',
  ADMIN: 'admin',
  MANAGER: 'manager',
  SALES: 'sales',
  SCHEDULER: 'scheduler',
  CREW: 'crew',
  CLIENT: 'client'
};

const ACTIONS = {
  CREATE: 'create',
  READ: 'read',
  UPDATE: 'update',
  DELETE: 'delete',
  LIST: 'list'
};

const RESOURCES = {
  CLIENTS: 'clients',
  PROPERTIES: 'properties',
  CONTACTS: 'contacts',
  LEADS: 'leads',
  QUOTES: 'quotes',
  JOBS: 'jobs',
  INVOICES: 'invoices',
  PAYMENTS: 'payments',
  EMPLOYEES: 'employees',
  CREWS: 'crews',
  EQUIPMENT: 'equipment',
  SCHEDULING: 'scheduling',
  ANALYTICS: 'analytics',
  AUTOMATION: 'automation',
  AI: 'ai',
  SETTINGS: 'settings',
  TEMPLATES: 'templates'
};

const PERMISSIONS_MATRIX = {
  [RESOURCES.CLIENTS]: {
    [ROLES.OWNER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.MANAGER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.SALES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.LIST],
    [ROLES.SCHEDULER]: [ACTIONS.READ, ACTIONS.LIST],
    [ROLES.CREW]: [ACTIONS.READ],
    [ROLES.CLIENT]: []
  },
  [RESOURCES.PROPERTIES]: {
    [ROLES.OWNER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.MANAGER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.SALES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.LIST],
    [ROLES.SCHEDULER]: [ACTIONS.READ, ACTIONS.LIST],
    [ROLES.CREW]: [ACTIONS.READ],
    [ROLES.CLIENT]: []
  },
  [RESOURCES.CONTACTS]: {
    [ROLES.OWNER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.MANAGER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.SALES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.LIST],
    [ROLES.SCHEDULER]: [ACTIONS.READ, ACTIONS.LIST],
    [ROLES.CREW]: [ACTIONS.READ],
    [ROLES.CLIENT]: []
  },
  [RESOURCES.LEADS]: {
    [ROLES.OWNER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.MANAGER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.SALES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.SCHEDULER]: [ACTIONS.READ, ACTIONS.LIST],
    [ROLES.CREW]: [],
    [ROLES.CLIENT]: []
  },
  [RESOURCES.QUOTES]: {
    [ROLES.OWNER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.MANAGER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.SALES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.SCHEDULER]: [ACTIONS.READ, ACTIONS.LIST],
    [ROLES.CREW]: [],
    [ROLES.CLIENT]: []
  },
  [RESOURCES.JOBS]: {
    [ROLES.OWNER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.MANAGER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.SALES]: [ACTIONS.READ, ACTIONS.LIST],
    [ROLES.SCHEDULER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.CREW]: [ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.CLIENT]: []
  },
  [RESOURCES.INVOICES]: {
    [ROLES.OWNER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.MANAGER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.SALES]: [ACTIONS.READ, ACTIONS.LIST],
    [ROLES.SCHEDULER]: [ACTIONS.READ, ACTIONS.LIST],
    [ROLES.CREW]: [],
    [ROLES.CLIENT]: []
  },
  [RESOURCES.PAYMENTS]: {
    [ROLES.OWNER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.MANAGER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.LIST],
    [ROLES.SALES]: [ACTIONS.READ, ACTIONS.LIST],
    [ROLES.SCHEDULER]: [],
    [ROLES.CREW]: [],
    [ROLES.CLIENT]: []
  },
  [RESOURCES.EMPLOYEES]: {
    [ROLES.OWNER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.MANAGER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.LIST],
    [ROLES.SALES]: [ACTIONS.READ, ACTIONS.LIST],
    [ROLES.SCHEDULER]: [ACTIONS.READ, ACTIONS.LIST],
    [ROLES.CREW]: [ACTIONS.READ],
    [ROLES.CLIENT]: []
  },
  [RESOURCES.CREWS]: {
    [ROLES.OWNER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.MANAGER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.LIST],
    [ROLES.SALES]: [ACTIONS.READ, ACTIONS.LIST],
    [ROLES.SCHEDULER]: [ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.LIST],
    [ROLES.CREW]: [ACTIONS.READ],
    [ROLES.CLIENT]: []
  },
  [RESOURCES.EQUIPMENT]: {
    [ROLES.OWNER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.MANAGER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.LIST],
    [ROLES.SALES]: [ACTIONS.READ, ACTIONS.LIST],
    [ROLES.SCHEDULER]: [ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.LIST],
    [ROLES.CREW]: [ACTIONS.READ],
    [ROLES.CLIENT]: []
  },
  [RESOURCES.SCHEDULING]: {
    [ROLES.OWNER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.MANAGER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.SALES]: [ACTIONS.READ, ACTIONS.LIST],
    [ROLES.SCHEDULER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.CREW]: [ACTIONS.READ],
    [ROLES.CLIENT]: []
  },
  [RESOURCES.ANALYTICS]: {
    [ROLES.OWNER]: [ACTIONS.READ, ACTIONS.LIST],
    [ROLES.ADMIN]: [ACTIONS.READ, ACTIONS.LIST],
    [ROLES.MANAGER]: [ACTIONS.READ, ACTIONS.LIST],
    [ROLES.SALES]: [ACTIONS.READ, ACTIONS.LIST],
    [ROLES.SCHEDULER]: [ACTIONS.READ, ACTIONS.LIST],
    [ROLES.CREW]: [],
    [ROLES.CLIENT]: []
  },
  [RESOURCES.AUTOMATION]: {
    [ROLES.OWNER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.MANAGER]: [ACTIONS.READ, ACTIONS.LIST],
    [ROLES.SALES]: [],
    [ROLES.SCHEDULER]: [],
    [ROLES.CREW]: [],
    [ROLES.CLIENT]: []
  },
  [RESOURCES.AI]: {
    [ROLES.OWNER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.LIST],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.LIST],
    [ROLES.MANAGER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.LIST],
    [ROLES.SALES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.LIST],
    [ROLES.SCHEDULER]: [ACTIONS.READ],
    [ROLES.CREW]: [ACTIONS.READ],
    [ROLES.CLIENT]: []
  },
  [RESOURCES.SETTINGS]: {
    [ROLES.OWNER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.LIST],
    [ROLES.MANAGER]: [ACTIONS.READ, ACTIONS.LIST],
    [ROLES.SALES]: [ACTIONS.READ],
    [ROLES.SCHEDULER]: [ACTIONS.READ],
    [ROLES.CREW]: [ACTIONS.READ],
    [ROLES.CLIENT]: []
  },
  [RESOURCES.TEMPLATES]: {
    [ROLES.OWNER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.LIST],
    [ROLES.MANAGER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.LIST],
    [ROLES.SALES]: [ACTIONS.READ, ACTIONS.LIST],
    [ROLES.SCHEDULER]: [ACTIONS.READ, ACTIONS.LIST],
    [ROLES.CREW]: [ACTIONS.READ],
    [ROLES.CLIENT]: []
  }
};

function hasPermission(role, resource, action) {
  const resourcePermissions = PERMISSIONS_MATRIX[resource];
  if (!resourcePermissions) {
    return false;
  }
  
  const rolePermissions = resourcePermissions[role];
  if (!rolePermissions) {
    return false;
  }
  
  return rolePermissions.includes(action);
}

function getPermittedActions(role, resource) {
  const resourcePermissions = PERMISSIONS_MATRIX[resource];
  if (!resourcePermissions) {
    return [];
  }
  
  return resourcePermissions[role] || [];
}

function getRoleHierarchy(role) {
  const hierarchy = {
    [ROLES.OWNER]: 100,
    [ROLES.ADMIN]: 90,
    [ROLES.MANAGER]: 70,
    [ROLES.SALES]: 50,
    [ROLES.SCHEDULER]: 50,
    [ROLES.CREW]: 30,
    [ROLES.CLIENT]: 10
  };
  
  return hierarchy[role] || 0;
}

function isRoleAtLeast(userRole, requiredRole) {
  return getRoleHierarchy(userRole) >= getRoleHierarchy(requiredRole);
}

module.exports = {
  ROLES,
  ACTIONS,
  RESOURCES,
  PERMISSIONS_MATRIX,
  hasPermission,
  getPermittedActions,
  getRoleHierarchy,
  isRoleAtLeast
};
