steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/treepro-ai-backend:$COMMIT_SHA', '.']
  # Push the container image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/treepro-ai-backend:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'treepro-ai-backend' # Choose your Cloud Run service name
      - '--image'
      - 'gcr.io/$PROJECT_ID/treepro-ai-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1' # Choose your preferred region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # Allows public access, adjust as needed
      - '--port'
      - '3001' # Specify the port your app listens on
images:
  - 'gcr.io/$PROJECT_ID/treepro-ai-backend:$COMMIT_SHA'