steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/treepro-ai-backend:$COMMIT_SHA', '-f', 'backend/Dockerfile', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/treepro-ai-backend:$COMMIT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'treepro-ai-backend' # Your Cloud Run service name
  - '--image'
  - 'gcr.io/$PROJECT_ID/treepro-ai-backend:$COMMIT_SHA'
  - '--region'
  - 'us-central1' # Your preferred region
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated' # Allows public access to your API
  - '--port'
  - '3001' # The port your app listens on inside the container
  # Add environment variables for the database connection here
  # - '--set-env-vars'
  # - 'DATABASE_URL=YOUR_POSTGRES_CONNECTION_STRING'
  # It is more secure to use Secret Manager for database credentials.

images:
- 'gcr.io/$PROJECT_ID/treepro-ai-backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
