steps:
# Build the container image using the backend directory as context
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/treepro-ai-backend:$COMMIT_SHA', '-f', 'backend/Dockerfile', './backend'] # Use backend/Dockerfile and backend context

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/treepro-ai-backend:$COMMIT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'treepro-ai-backend' # Your Cloud Run service name
  - '--image'
  - 'gcr.io/$PROJECT_ID/treepro-ai-backend:$COMMIT_SHA'
  - '--region'
  - 'us-central1' # Your preferred region
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated' # Allows public access - review if this is needed
  - '--port'
  - '3001' # Matches your server.js
  # IMPORTANT: Set database environment variables here or via Secret Manager
  - '--set-env-vars'
  - '^##^DATABASE_URL=postgresql://USER:PASSWORD@HOST:PORT/DATABASE' # Use Cloud Run's format (^##^ for delimiters)

images:
- 'gcr.io/$PROJECT_ID/treepro-ai-backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY