import React from 'react';
import { X, MapPin, Clock, AlertTriangle, MoveUp, MoveDown, Send, RefreshCcw, Users } from 'lucide-react';
import { RouteOptimizationResult, RouteStop } from '../types';

interface RoutePlanDrawerProps {
  isOpen: boolean;
  routePlan: RouteOptimizationResult | null;
  onClose: () => void;
  onReorder: (jobId: string, direction: 'up' | 'down') => void;
  onNotify: (jobId: string, etaMinutes?: number) => void;
  onReoptimize?: () => void;
}

const RoutePlanDrawer: React.FC<RoutePlanDrawerProps> = ({
  isOpen,
  routePlan,
  onClose,
  onReorder,
  onNotify,
  onReoptimize
}) => {
  if (!isOpen || !routePlan) return null;

  const getStopBadge = (stop: RouteStop) => {
    if (stop.status === 'In Progress') return 'bg-blue-100 text-blue-800';
    if (stop.status === 'Scheduled') return 'bg-green-100 text-green-800';
    return 'bg-amber-100 text-amber-800';
  };

  return (
    <div className="fixed inset-0 z-40 flex items-start justify-end bg-black/50 backdrop-blur-sm">
      <div className="absolute inset-0" onClick={onClose} aria-label="Close route plan overlay" />
      <aside className="relative w-full max-w-4xl h-full bg-white shadow-2xl border-l border-brand-gray-200 overflow-y-auto">
        <div className="flex items-center justify-between px-6 py-4 border-b border-brand-gray-200 bg-brand-gray-50">
          <div>
            <p className="text-xs font-medium text-brand-gray-500">Route plan</p>
            <h2 className="text-lg font-semibold text-brand-gray-900">
              {routePlan.crewName || 'Crew'} • {routePlan.date}
            </h2>
            <p className="text-xs text-brand-gray-500">{routePlan.status === 'finalized' ? 'Ready to dispatch' : 'Draft generated by optimizer'}</p>
          </div>
          <div className="flex items-center gap-2">
            {onReoptimize && (
              <button
                onClick={onReoptimize}
                className="inline-flex items-center gap-2 px-3 py-2 text-sm font-medium text-brand-gray-700 bg-white border border-brand-gray-300 rounded-md hover:bg-brand-gray-100"
              >
                <RefreshCcw className="w-4 h-4" />
                Re-run
              </button>
            )}
            <button
              onClick={onClose}
              className="p-2 text-brand-gray-500 hover:text-brand-gray-700 rounded-md hover:bg-brand-gray-100"
              aria-label="Close route plan"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        <div className="p-6 space-y-6">
          <div className="grid md:grid-cols-3 gap-4">
            <div className="p-4 rounded-lg border border-brand-gray-200 bg-brand-gray-50">
              <p className="text-xs font-medium text-brand-gray-500">Distance</p>
              <p className="text-xl font-semibold text-brand-gray-900">{routePlan.totalDistanceMiles.toFixed(1)} mi</p>
            </div>
            <div className="p-4 rounded-lg border border-brand-gray-200 bg-brand-gray-50">
              <p className="text-xs font-medium text-brand-gray-500">Drive time</p>
              <p className="text-xl font-semibold text-brand-gray-900">{Math.round(routePlan.totalDriveMinutes)} min</p>
            </div>
            <div className="p-4 rounded-lg border border-brand-gray-200 bg-brand-gray-50">
              <p className="text-xs font-medium text-brand-gray-500">Total effort</p>
              <p className="text-xl font-semibold text-brand-gray-900">{routePlan.totalEstimatedHours.toFixed(1)} hrs</p>
            </div>
          </div>

          {routePlan.warnings && routePlan.warnings.length > 0 && (
            <div className="p-4 rounded-lg border border-amber-200 bg-amber-50 flex items-start gap-3">
              <AlertTriangle className="w-5 h-5 text-amber-600 mt-0.5" />
              <div>
                <p className="text-sm font-semibold text-amber-800">Optimizer warnings</p>
                <ul className="mt-1 space-y-1 text-sm text-amber-700">
                  {routePlan.warnings.map((warning, idx) => (
                    <li key={idx}>• {warning}</li>
                  ))}
                </ul>
              </div>
            </div>
          )}

          <div className="space-y-3">
            {routePlan.stops.map((stop, index) => (
              <div key={stop.jobId} className="p-4 rounded-lg border border-brand-gray-200 bg-white shadow-sm">
                <div className="flex items-start gap-3">
                  <span className="inline-flex h-10 w-10 items-center justify-center rounded-full bg-brand-cyan-50 text-brand-cyan-700 font-semibold">
                    #{stop.order}
                  </span>
                  <div className="flex-1">
                    <div className="flex items-center gap-2">
                      <p className="text-sm font-semibold text-brand-gray-900">{stop.customerName}</p>
                      <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${getStopBadge(stop)}`}>
                        {stop.status}
                      </span>
                    </div>
                    <p className="text-xs text-brand-gray-600">ETA {stop.arrivalTimeLocal} • {stop.estimatedDurationHours.toFixed(1)}h on site</p>
                    <p className="mt-1 inline-flex items-center gap-2 text-xs text-brand-gray-600">
                      <MapPin className="w-4 h-4" />
                      {stop.location.address || 'Location pending'}
                    </p>
                    <p className="mt-1 inline-flex items-center gap-2 text-xs text-brand-gray-600">
                      <Clock className="w-4 h-4" /> {Math.round(stop.travelDurationMinutes)} min drive • {stop.travelDistanceMiles.toFixed(1)} mi
                    </p>
                    {stop.notes && <p className="mt-2 text-xs text-brand-gray-700">{stop.notes}</p>}

                    <div className="mt-3 flex flex-wrap gap-2">
                      <button
                        onClick={() => onNotify(stop.jobId, Math.round(stop.travelDurationMinutes))}
                        className="inline-flex items-center gap-2 px-3 py-1.5 text-xs font-medium text-white bg-brand-cyan-600 rounded-md hover:bg-brand-cyan-700"
                      >
                        <Send className="w-4 h-4" />
                        Notify "On my way"
                      </button>
                      <div className="inline-flex items-center gap-1">
                        <button
                          onClick={() => onReorder(stop.jobId, 'up')}
                          disabled={index === 0}
                          className="p-2 rounded-md border border-brand-gray-200 text-brand-gray-600 hover:bg-brand-gray-50 disabled:opacity-40"
                          aria-label="Move stop earlier"
                        >
                          <MoveUp className="w-4 h-4" />
                        </button>
                        <button
                          onClick={() => onReorder(stop.jobId, 'down')}
                          disabled={index === routePlan.stops.length - 1}
                          className="p-2 rounded-md border border-brand-gray-200 text-brand-gray-600 hover:bg-brand-gray-50 disabled:opacity-40"
                          aria-label="Move stop later"
                        >
                          <MoveDown className="w-4 h-4" />
                        </button>
                      </div>
                    </div>
                  </div>
                  <div className="flex flex-col items-end gap-2 text-xs text-brand-gray-500">
                    <span className="inline-flex items-center gap-1 px-2 py-1 rounded-full bg-brand-gray-100 text-brand-gray-700">
                      <Users className="w-4 h-4" /> {stop.assignedCrewIds.length} assigned
                    </span>
                    <span className="font-mono">{stop.jobId}</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </aside>
    </div>
  );
};

export default RoutePlanDrawer;
